name: Hello CI
on: push

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "created by job one" > secret.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-file
          path: secret.txt

  job-two:
    needs: job-one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: my-file
      - run: cat secret.txt

